### ISSUE TITLE
词典显示 bug

### ISSUE THREAD

**Issue by 0ZDragon** [mumu-lhl/Ciyue#17]
汉语大词典乱码，大字典图片显示有问题
以及目前似乎还不支持词典内部的自定义字体和软件层面的自定义字体，和词典图片的显示
https://pan.huang1111.cn/s/1Q6Y8Fv

**Comment by mumu-lhl** [comment]
https://github.com/mumu-lhl/dict_reader/commit/734f47cf652c54d59e04f0de722d3a830cb76d2a 修复了乱码

**Comment by mumu-lhl** [comment]
https://github.com/mumu-lhl/dict_reader/commit/912563ff086c7ff20c03710ea742d4451c4d177a 修复了图片显示

**Comment by mumu-lhl** [comment]
#28 已加入自定义字体功能
