### ISSUE TITLE
自動備份詞彙本

### ISSUE THREAD

**Issue by curability4apish** [mumu-lhl/Ciyue#34]
建議新增自動備份詞彙本的功能，每儲存一條單字就立即覆寫備份，以防止因不明原因的程式崩潰或故障所導致的資料遺失。這確實在剛才發生了，app 無故無法載入，只好重設 app才能恢復正常。

**Comment by mumu-lhl** [comment]
a53ee9b844c55e9e3f1575ace2cda425de383ab3 已实现该功能，开启“自动导出”选项后，导出一次就可以自动导出了
