### ISSUE TITLE
Remove DependencyInfoBlock for F-Droid

### ISSUE THREAD

**Issue by linsui** [mumu-lhl/Ciyue#43]
**Describe the bug**
We find that there is a `DependencyInfoBlock` in your apk. It's a [Frosting](https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1) block in the signing block. It's added by AGP and signed by Google's public key so it can't be read by anyone else except Google.

Could you please disable it with the following code?

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

Thanks!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information (please complete the following information):**

**Additional context**

**Comment by mumu-lhl** [comment]
v0.11.1 has removed.

**Comment by linsui** [comment]
Thanks!
