### ISSUE TITLE
Better UX when searching a word not in the dict from the context

### ISSUE THREAD

**Issue by linsui** [mumu-lhl/Ciyue#64]
**Is your feature request related to a problem? Please describe.**
When searching a word not in the dict from the context ciyue shows an empty home screen which is a little confusing.

**Describe the solution you'd like**
The search request should be filled in the search field. And maybe a message can be displayed as a toast.

**Describe alternatives you've considered**
Return to the previous app with an error message.

**Additional context**

**Comment by mumu-lhl** [comment]
Now:
![Screenshot](https://github.com/user-attachments/assets/b7c92fbd-77f4-430d-bc8c-be24593d7aa6)

**Comment by linsui** [comment]
Thanks!
