### ISSUE TITLE
使用的问题

### ISSUE THREAD

**Issue by marigold233** [mumu-lhl/Ciyue#7]
我发现我搜词出来的结果和项目介绍截图的不一样。  
![Screenshot_20240827-081228_词悦.png](https://github.com/user-attachments/assets/e2a527c5-7e45-4ca8-8df9-027d9c94220d)

![358161926-6de46e3e-c032-4c7b-9dfc-fd11b70cff52.png](https://github.com/user-attachments/assets/647bc240-6451-45fe-aa5b-e7aa9049817d)

**Comment by mumu-lhl** [comment]
在 mdx 文件的目录下存在同名的 mdd 文件吗？mdd 文件包含了所需的资源（如 CSS、JS、图片）

**Comment by marigold233** [comment]
> 看上去缺少了资源。
> 
> 在 mdx 文件的目录下存在同名的 mdd 文件吗？
> 
> mdd 文件包含了所需的资源（如 CSS、JS、图片）。词悦会寻找同名的 mdd 文件。

已解决
