### ISSUE TITLE
Please remove the unnecessary permissions

### ISSUE THREAD

**Issue by serrq** [mumu-lhl/Ciyue#8]
I can download dictionaries aside the app. So app remains safe without any internet permission.

As for "all files permission" you can replace it with SAF.

![1000118028](https://github.com/user-attachments/assets/4f820647-8f3e-4282-9e12-509da58f0816)

![1000118030](https://github.com/user-attachments/assets/4797074b-265b-4a79-a8df-ba5dc91eb90a)

**Comment by mumu-lhl** [comment]
The internet permission is for WebView to display words.

"all files permission" is to read mdd that the resources of mdx.

These permissions are necessary.

**Comment by mumu-lhl** [comment]
See <https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15597#note_2056149689>.
