### ISSUE TITLE
Look up history 

### ISSUE THREAD

**Issue by Mirpri** [mumu-lhl/Ciyue#88]
Add a dictionary look up history for easier access to search for words again. 
I think is a good idea to display history lookups on the homepage before I type anything as the homepage is dull in current version. 😀

**Comment by mumu-lhl** [comment]
Included in [v1.0.0-alpha.2](https://github.com/mumu-lhl/Ciyue/releases/tag/v1.0.0-alpha.2) :), update if you don't mind that there may be some bugs.
