### ISSUE TITLE
Ignore spaces in the end

### ISSUE THREAD

**Issue by Mirpri** [mumu-lhl/Ciyue#89]
When I type a word in the search  bar, sometimes my IME automatically adds a space to the end of the word. That space makes leads to no-result situation, so I have to delete it. 
I wish the app could ignore spaces in the end of string to further enhance the experience. (though it's only a subtle matter)

**Comment by mumu-lhl** [comment]
Included in v0.15.1 :)

**Comment by AmarDarker** [comment]
It still has this problem, after a space, word can not be identified. 

https://github.com/user-attachments/assets/4e958b9b-d736-486b-beb3-ab0ee0297d5e

App version:  1.19.0
OS:Android15 
Device: SM-X510/ samsung
